version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
